# version: '3.8'

# Define all services that make up the SENG 468 day trading system
services:
  # API Gateway service - Entry point for all client requests
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:5000"  # Maps container port 5000 to host port 4000
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5000
      - TRADING_SERVICE_URL=http://trading-service:8000
      - MATCHING_ENGINE_URL=http://matching-engine:8080
      - LOGGING_SERVICE_URL=http://logging-service:5000
      - FLASK_ENV=production
      - SECRET_KEY=${API_GATEWAY_SECRET_KEY:-default_secret_key}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
      - PYTHONUNBUFFERED=1
      # Rate limiting
      - RATE_LIMIT_ENABLED=True
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW=60

        # Circuit breaker
      - CIRCUIT_BREAKER_ENABLED=True
      - CIRCUIT_BREAKER_THRESHOLD=5
      - CIRCUIT_BREAKER_TIMEOUT=60

        # Logging
      - LOG_LEVEL=DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - auth-service
      - trading-service
      - matching-engine
      - logging-service
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Authentication service - Handles user authentication and authorization
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4001:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/auth_db
      - FLASK_ENV=production
      - SECRET_KEY=${AUTH_SERVICE_SECRET_KEY:-default_secret_key}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default_secret_key}
    depends_on:
      - db
    networks:
      - trading-network
    restart: unless-stopped
    volumes:
      - auth-logs:/app/logs
      - ./auth-service:/app 

  # Trading service - Handles trading operations and business logic
  trading-service:
    build: 
      context: ./trading-service
      dockerfile: Dockerfile
    ports:
      - "4002:8000"
    environment:
      - DB_NAME=trading_db
      - DB_USER=${POSTGRES_USER:-user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=trading_service_project.settings
      - DJANGO_SECRET_KEY=${TRADING_SERVICE_SECRET_KEY:-default_secret_key}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-default_secret_key}
      - DJANGO_DEBUG=1
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    networks:
      - trading-network
    restart: unless-stopped
    volumes:
      - trading-logs:/app/logs
      - trading-static:/app/staticfiles
      - ./trading-service:/app

  # Matching Engine service - Handles order matching logic
  matching-engine:
    build: 
      context: ./matching-engine
      dockerfile: Dockerfile
    ports:
      - "4003:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - DB_NAME=matching_db
      - SERVICE_AUTH_TOKEN=${SERVICE_AUTH_TOKEN:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDMzOTQxMjMsInN1YiI6eyJpZCI6OTk5LCJ1c2VybmFtZSI6InN5c3RlbSIsImFjY291bnRfdHlwZSI6InN5c3RlbSJ9LCJpYXQiOjE3NDA4MDU3MjN9.y5_3YSiw6zVpygAu0rv2h5SihFcPewITmMsRG9Os_dU}
      - TRADING_SERVICE_URL=http://api-gateway:5000/transaction/processTransaction
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trading-network
    restart: unless-stopped
    volumes:
      - matching-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Logging service - Handles system-wide logging and auditing
  logging-service:
    build: 
      context: ./logging-service
      dockerfile: Dockerfile
    ports:
      - "4004:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/logging_db
      - FLASK_ENV=production
      - SECRET_KEY=${LOGGING_SERVICE_SECRET_KEY:-default_secret_key}
    depends_on:
      - db
    networks:
      - trading-network
    restart: unless-stopped
    volumes:
      - logging-logs:/app/logs

  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_MULTIPLE_DATABASES=auth_db,trading_db,matching_db,logging_db
      # This sets the authentication method for PostgreSQL
      - POSTGRES_INITDB_ARGS=--auth=md5
    ports:
      - "5432:5432"
    networks:
      - trading-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the initialization script
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define networks
networks:
  trading-network:
    driver: bridge

# Define volumes
volumes:
  postgres_data:
  auth-logs:
  trading-logs:
  trading-static:
  matching-logs:
  logging-logs: 